name: TNTRun_reloaded
main: tntrun.TNTRun
softdepend: [WorldEdit, Vault, HeadsPlus, mcMMO, PlaceholderAPI]
version: ${project.version}
api-version: 1.13
author: [steve4744]
commands:
  tntrunsetup:
    description: TNTRun arena setup commands
    aliases: trsetup
  tntrun:
    description: TNTRun game commands
    aliases: tr
  tntrunconsole:
    description: TNTRun console commands
    aliases: trconsole
permissions:
  tntrun.join:
    description: used to control who can play TNTRun and where.
    default: true
  tntrun.leave:
    description: used to control who can leave TNTRun arenas.
    default: true
  tntrun.setup:
    description: used to create and modify arenas and gameplay
    default: op
  tntrun.version.check:
    description: display new version message on player join
    default: op
  tntrun.heads:
    description: control who can use HeadsPlus in-game
    default: true
  tntrun.shop:
    description: allow players to buy any shop item (if they have money)
    default: true
  tntrun.joinmenu:
    description: allow players to use the join menu
    default: true
  tntrun.start:
    description: allow players to start an arena before the minimum players is reached
    default: op
  tntrun.spectate:
    description: allow players to join the arena as a spectator
    default: op
  tntrun.listrewards:
    description: allow players to list the arena rewards
    default: true